language: node_js
node_js:
  - '4'
  - '6'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-stratic' ]; then cd .. && eval "mv $currentfolder generator-stratic" && cd generator-stratic; fi

